module.exports = {

    StartingMatches: [
        {
            home: 'Fortaleza',
            away: 'Atlético-MG',
            homeScore: 2,
            awayScore: 2,
            date: new Date("2019-11-02T17:00:00"),
            round: "30",
            venue: "Castelão",
            city: "Fortaleza",
            state: "CE",
            country: "Brasil"
        },
        {
            home: 'Corinthians',
            away: 'Fortaleza',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-06T19:30:00"),
            round: "31",
            venue: "Arena Corinthians",
            city: "São Paulo",
            state: "SP",
            country: "Brasil"
        },
        {
            home: 'Fortaleza',
            away: 'Ceará',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-10T19:00:00"),
            round: "32",
            venue: "Castelão",
            city: "Fortaleza",
            state: "CE",
            country: "Brasil"
        },
        {
            home: 'Fortaleza',
            away: 'CSA',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-16T21:00:00"),
            round: "33",
            venue: "Castelão",
            city: "Fortaleza",
            state: "CE",
            country: "Brasil"
        },
        {
            home: 'Internacional',
            away: 'Fortaleza',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-24T19:00:00"),
            round: "34",
            venue: "Beira-Rio",
            city: "Porto Alegre",
            state: "RS",
            country: "Brasil"
        },
        {
            home: 'Fortaleza',
            away: 'Santos',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-28T19:00:00"),
            round: "35",
            venue: "Castelão",
            city: "Fortaleza",
            state: "CE",
            country: "Brasil"
        },
        {
            home: 'Goiás',
            away: 'Fortaleza',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-12-01T16:00:00"),
            round: "36",
            venue: "Serra Dourada",
            city: "Goiânia",
            state: "GO",
            country: "Brasil"
        },
        {
            home: 'Fluminense',
            away: 'Fortaleza',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date(2019, 11, 04),
            round: "37",
            venue: undefined,
            city: undefined,
            state: undefined,
            country: undefined
        },
        {
            home: 'Fortaleza',
            away: 'Bahia',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date(2019, 11, 08),
            round: "38",
            venue: undefined,
            city: undefined,
            state: undefined,
            country: undefined
        },
        {
            home: 'Athletico-PR',
            away: 'CSA',
            homeScore: 1,
            awayScore: 0,
            date: new Date("2019-11-03T18:00:00"),
            round: "30",
            venue: "Arena da Baixada",
            city: "Curitiba",
            state: "PR",
            country: "Brasil"
        },
        {
            home: 'Grêmio',
            away: 'CSA',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-07T21:00:00"),
            round: "31",
            venue: "Arena do Grêmio",
            city: "Porto Alegre",
            state: "RS",
            country: "Brasil"
        },
        {
            home: 'CSA',
            away: 'Vasco da Gama',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-10T19:00:00"),
            round: "32",
            venue: "Rei Pelé",
            city: "Maceió",
            state: "AL",
            country: "Brasil"
        },
        {
            home: 'CSA',
            away: 'Fluminense',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-25T20:00:00"),
            round: "34",
            venue: "Rei Pelé",
            city: "Maceió",
            state: "AL",
            country: "Brasil"
        },
        {
            home: 'Cruzeiro',
            away: 'CSA',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-11-28T21:30:00"),
            round: "35",
            venue: "Mineirão",
            city: "Belo Horizonte",
            state: "MG",
            country: "Brasil"
        },
        {
            home: 'CSA',
            away: 'Bahia',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date("2019-12-01T18:00:00"),
            round: "36",
            venue: "Rei Pelé",
            city: "Maceió",
            state: "AL",
            country: "Brasil"
        },
        {
            home: 'Chapecoense',
            away: 'CSA',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date(2019, 11, 03),
            round: "37",
            venue: undefined,
            city: undefined,
            state: undefined,
            country: undefined
        },
        {
            home: 'CSA',
            away: 'São Paulo',
            homeScore: undefined,
            awayScore: undefined,
            date: new Date(2019, 11, 07),
            round: "38",
            venue: undefined,
            city: undefined,
            state: undefined,
            country: undefined
        },

    ]

}